image: openjdk:8u252-jdk

before_script:
  - export GRADLE_USER_HOME=./.gradle

build:
  stage: build
  script:
    - ./gradlew --build-cache build
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .gradle
